use std::path::Path;

use editor_core::{ChangedEntity, JobId, Project, ProjectRevision, RequestId};
use job_system::{JobFailure, JobKind, JobSnapshot, JobState};
use project_io::{RecoveryCandidate, RecoverySnapshot};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectSnapshotDto {
    pub revision: ProjectRevision,
    pub project: Project,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CommandResultDto {
    pub request_id: RequestId,
    pub revision: ProjectRevision,
    pub changed_entities: Vec<ChangedEntity>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecoveryCandidateDto {
    pub path: String,
    pub revision: ProjectRevision,
    pub created_at_ms: u64,
}

impl From<RecoveryCandidate> for RecoveryCandidateDto {
    fn from(candidate: RecoveryCandidate) -> Self {
        Self {
            path: candidate.path.to_string_lossy().into_owned(),
            revision: candidate.revision,
            created_at_ms: candidate.created_at_ms,
        }
    }
}

impl From<RecoverySnapshot> for RecoveryCandidateDto {
    fn from(snapshot: RecoverySnapshot) -> Self {
        Self {
            path: snapshot.path.to_string_lossy().into_owned(),
            revision: snapshot.revision,
            created_at_ms: snapshot.created_at_ms,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JobEventDto {
    pub job_id: JobId,
    pub kind: JobKind,
    pub state: JobState,
    pub progress: f32,
    pub source_revision: ProjectRevision,
    pub failure: Option<JobFailure>,
}

impl From<JobSnapshot> for JobEventDto {
    fn from(snapshot: JobSnapshot) -> Self {
        Self {
            job_id: snapshot.context.job_id,
            kind: snapshot.kind,
            state: snapshot.state,
            progress: snapshot.progress,
            source_revision: snapshot.context.source_revision,
            failure: snapshot.failure,
        }
    }
}

pub const TYPESCRIPT_CONTRACTS: &str = "// @generated by apps/desktop/src-tauri/src/contracts.rs\n// Do not edit by hand. Regenerate through the Rust contract generator.\n\nexport type UUID = string;\nexport type ProjectId = UUID;\nexport type SequenceId = UUID;\nexport type TrackId = UUID;\nexport type ClipId = UUID;\nexport type MediaId = UUID;\nexport type JobId = UUID;\nexport type RequestId = UUID;\nexport type ProjectRevision = number;\nexport type TimeUs = number;\n\nexport type TrackKind = \"Video\" | \"Overlay\" | \"Audio\" | \"Text\" | \"Subtitle\";\nexport type ClipKind = \"Video\" | \"Audio\" | \"Image\" | \"Text\";\nexport type TextAlignment = \"Left\" | \"Center\" | \"Right\";\nexport type TransitionKind = \"CrossDissolve\" | \"Fade\" | \"DipToBlack\" | \"DipToWhite\";\nexport type JobKind =\n  | \"Thumbnail\"\n  | \"Waveform\"\n  | \"Proxy\"\n  | \"PreviewRender\"\n  | \"Transcription\"\n  | \"SilenceAnalysis\"\n  | \"HighlightAnalysis\"\n  | \"Export\"\n  | \"ModelDownload\";\nexport type JobState = \"Queued\" | \"Running\" | \"Completed\" | \"Failed\" | \"Cancelled\";\n\nexport interface Project {\n  id: ProjectId;\n  name: string;\n  settings: ProjectSettings;\n  media: MediaRef[];\n  sequences: Sequence[];\n}\n\nexport interface ProjectSettings {\n  default_sequence_width: number;\n  default_sequence_height: number;\n  default_sequence_fps: number;\n}\n\nexport interface MediaRef {\n  id: MediaId;\n  absolute_path: string;\n  project_relative_path: string | null;\n  file_size: number;\n  duration: TimeUs | null;\n  width: number | null;\n  height: number | null;\n}\n\nexport interface Sequence {\n  id: SequenceId;\n  name: string;\n  width: number;\n  height: number;\n  fps: number;\n  tracks: Track[];\n  subtitle_segments: SubtitleSegment[];\n  subtitle_style: SubtitleStyle;\n  markers: Marker[];\n}\n\nexport interface Track {\n  id: TrackId;\n  name: string;\n  kind: TrackKind;\n  muted: boolean;\n  locked: boolean;\n  hidden: boolean;\n  clips: Clip[];\n}\n\nexport interface Clip {\n  id: ClipId;\n  kind: ClipKind;\n  media_id: MediaId | null;\n  source_in: TimeUs;\n  source_out: TimeUs;\n  timeline_start: TimeUs;\n  timeline_end: TimeUs;\n  transform: Transform;\n  color: ColorAdjustments;\n  audio: AudioState;\n  speed: number;\n  transition: Transition | null;\n  text: TextState | null;\n}\n\nexport interface Transform {\n  position_x: number;\n  position_y: number;\n  scale_x: number;\n  scale_y: number;\n  rotation_degrees: number;\n  opacity: number;\n  crop: Crop;\n}\n\nexport interface Crop {\n  left: number;\n  top: number;\n  right: number;\n  bottom: number;\n}\n\nexport interface ColorAdjustments {\n  exposure: number;\n  contrast: number;\n  highlights: number;\n  shadows: number;\n  saturation: number;\n  temperature: number;\n  tint: number;\n}\n\nexport interface AudioState {\n  volume: number;\n  gain_db: number;\n  muted: boolean;\n  fade_in: TimeUs;\n  fade_out: TimeUs;\n}\n\nexport interface Transition {\n  kind: TransitionKind;\n  duration: TimeUs;\n}\n\nexport interface SubtitleSegment {\n  start: TimeUs;\n  end: TimeUs;\n  text: string;\n}\n\nexport interface SubtitleStyle {\n  text_style: TextStyle;\n  active_word_color: string | null;\n}\n\nexport interface TextState {\n  text: string;\n  style: TextStyle;\n}\n\nexport interface TextStyle {\n  font_family: string;\n  font_size: number;\n  weight: number;\n  alignment: TextAlignment;\n  color: string;\n  stroke_color: string;\n  stroke_width: number;\n  shadow: boolean;\n  background: string | null;\n  opacity: number;\n}\n\nexport interface Marker {\n  id: UUID;\n  time: TimeUs;\n  label: string;\n}\n\nexport interface TimelineRange {\n  start: TimeUs;\n  end: TimeUs;\n}\n\nexport type ChangedEntity =\n  | { Media: MediaId }\n  | { Sequence: SequenceId }\n  | { Track: TrackId }\n  | { Clip: ClipId };\n\nexport type EditCommand =\n  | { ImportMedia: { media: MediaRef } }\n  | { RelinkMedia: { media_id: MediaId; media: MediaRef } }\n  | { AddSequence: { sequence: Sequence; index: number | null } }\n  | { AddClip: { sequence_id: SequenceId; track_id: TrackId; clip: Clip } }\n  | { DeleteClip: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId } }\n  | { MoveClip: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; timeline_start: TimeUs } }\n  | { TrimClip: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; source_in: TimeUs; source_out: TimeUs; timeline_start: TimeUs; timeline_end: TimeUs } }\n  | { SplitClip: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; split_at: TimeUs; right_clip_id: ClipId } }\n  | { DuplicateClip: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; duplicate_id: ClipId; timeline_start: TimeUs } }\n  | { RippleDelete: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId } }\n  | { ApplySilenceRemoval: { sequence_id: SequenceId; ranges: TimelineRange[] } }\n  | { AddTrack: { sequence_id: SequenceId; track: Track; index: number | null } }\n  | { RemoveTrack: { sequence_id: SequenceId; track_id: TrackId } }\n  | { ReorderTrack: { sequence_id: SequenceId; track_id: TrackId; new_index: number } }\n  | { SetTrackMute: { sequence_id: SequenceId; track_id: TrackId; muted: boolean } }\n  | { SetTrackLock: { sequence_id: SequenceId; track_id: TrackId; locked: boolean } }\n  | { SetTrackHidden: { sequence_id: SequenceId; track_id: TrackId; hidden: boolean } }\n  | { SetVolume: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; volume: number } }\n  | { NormalizeAudio: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; gain_db: number } }\n  | { SetAudioState: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; audio: AudioState } }\n  | { SetTransform: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; transform: Transform } }\n  | { SetColor: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; color: ColorAdjustments } }\n  | { SetSpeed: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; speed: number } }\n  | { AddTransition: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; transition: Transition } }\n  | { AddText: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; timeline_start: TimeUs; timeline_end: TimeUs; text: string; style: TextStyle } }\n  | { SetTextStyle: { sequence_id: SequenceId; track_id: TrackId; clip_id: ClipId; style: TextStyle } }\n  | { AddSubtitleSegments: { sequence_id: SequenceId; segments: SubtitleSegment[] } }\n  | { SetSubtitleSegments: { sequence_id: SequenceId; segments: SubtitleSegment[] } }\n  | { SetSubtitleStyle: { sequence_id: SequenceId; style: SubtitleStyle } }\n  | { AddMarker: { sequence_id: SequenceId; marker: Marker } }\n  | { RemoveMarker: { sequence_id: SequenceId; marker_id: UUID } };\n\nexport interface EditRequest {\n  request_id: RequestId;\n  expected_revision: ProjectRevision;\n  command: EditCommand;\n}\n\nexport interface ProjectSnapshotDto {\n  revision: ProjectRevision;\n  project: Project;\n}\n\nexport interface CommandResultDto {\n  request_id: RequestId;\n  revision: ProjectRevision;\n  changed_entities: ChangedEntity[];\n}\n\nexport type ErrorCategory = \"Domain\" | \"Project\" | \"Media\" | \"AiModel\" | \"Job\" | \"Filesystem\" | \"Capability\" | \"Internal\";\n\nexport interface AppErrorDto {\n  category: ErrorCategory;\n  code: string;\n  message: string;\n  retryable: boolean;\n  technical_detail: string;\n  component: string;\n  operation: string;\n  request_id: RequestId | null;\n  job_id: JobId | null;\n}\n\nexport interface JobFailure {\n  code: string;\n  stage: string;\n  retryable: boolean;\n  safe_message: string;\n  technical_detail: string;\n}\n\nexport interface JobSpec {\n  kind: JobKind;\n  request_id: RequestId;\n  project_id: ProjectId;\n  sequence_id: SequenceId;\n  source_revision: ProjectRevision;\n  cancellable: boolean;\n}\n\nexport interface JobEventDto {\n  job_id: JobId;\n  kind: JobKind;\n  state: JobState;\n  progress: number;\n  source_revision: ProjectRevision;\n  failure: JobFailure | null;\n}\n";

pub fn write_typescript_contract(path: &Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, TYPESCRIPT_CONTRACTS.as_bytes())
}
